# Generated by Django 5.0 on 2023-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField(max_length=15)),
                ('address', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
